#!/usr/bin/python3
# Check if Let's Encrypt certificates are still valid
# +------------------------------------------------------------------+
# |             ____ _               _        __  __ _  __           |
# |            / ___| |__   ___  ___| | __   |  \/  | |/ /           |
# |           | |   | '_ \ / _ \/ __| |/ /   | |\/| | ' /            |
# |           | |___| | | |  __/ (__|   <    | |  | | . \            |
# |            \____|_| |_|\___|\___|_|\_\___|_|  |_|_|\_\           |
# |                                                                  |
# | Copyright Mathias Kettner 2014             mk@mathias-kettner.de |
# +------------------------------------------------------------------+
#
# This file is part of Check_MK.
# The official homepage is at http://mathias-kettner.de/check_mk.
#
# check_mk is free software;  you can redistribute it and/or modify it
# under the  terms of the  GNU General Public License  as published by
# the Free Software Foundation in version 2.  check_mk is  distributed
# in the hope that it will be useful, but WITHOUT ANY WARRANTY;  with-
# out even the implied warranty of  MERCHANTABILITY  or  FITNESS FOR A
# PARTICULAR PURPOSE. See the  GNU General Public License for more de-
# tails. You should have  received  a copy of the  GNU  General Public
# License along with GNU Make; see the file  COPYING.  If  not,  write
# to the Free Software Foundation, Inc., 51 Franklin St,  Fifth Floor,
# Boston, MA 02110-1301 USA.
import subprocess 

def get_cert_names():
    # get output from certbot
    # check if more than one domain, name
    # parse output
    proc = subprocess.Popen(["certbot", "certificates"], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, universal_newlines=True)
    result = proc.stdout.read()

    result = result.split('\n')
    result.pop(0)
    result.pop(1)
    result.pop()
    result.pop()
    result.pop()
    wcl = len(result)

    if wcl > 8:
        multiple_domains = True
    else:
        multiple_domains = False

    #if multiple_domains:
    cert_names = []
    expire_dates = []
    res = {}
    for i in range(1,wcl,5):
        cert_names.append(result[i].split(':')[1])
    for i in range(3,wcl,5):
        expire_date = result[i].split('(')[1][6:].split(' ')[1]
        expire_dates.append(expire_date)

    for i in range(len(cert_names)):
        res[cert_names[i]] = expire_dates[i]

    return(res)

def create_check_info(certs):
    print("<<<letsencrypt:sep(0)>>>")
    for val in certs:
        print(val, certs[val])

certs = get_cert_names()
create_check_info(certs)
